id: P582667A8
initial_creation_type: input
source_metadata:
  title: Calling the Guru from Afar
  language: bo
  description: 'Devotional texts belonging to the genre of Calling the Guru from Afar
    (bla ma rgyang ''bod):'
  volume:
    24dd63d140744d5eb4e7aeb0f91c0ca5:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    36535e29e392482eb6f2237ec208269b:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Prayers
    c07d4602ff3443ef956abee1f8dd2a04:
      title: Calling the Guru From Afar
      parent: Prayers
    7746f35b992d4c008fb47134f3d9ad10:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Prayers
    3849930903304bb5bb9796f6cf36db8f:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    71458000cd2b4bb5815d12c6fbbf05a2:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
    42010e95543d4dc6b48c18a781a88af2:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    643a58098d41479a9a24f46e553dcb7f:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Prayers
    647b79d85ddd4abdaa76a6256399693a:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Prayers
    21c14ed628a345e99f15a7c9d6b3fe11:
      title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling
        the Guru from Afar'
      parent: Prayers
    2688d1920d914063b1d35c0f6f5b2d95:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Prayers
    08596dbd064a4db08cfe9cd03219620e:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    10e5a6255bf340199261b9914a9e4f69:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Prayers
    b1d3ff90e47b4dd99d55138f64710c2d:
      title: Calling the Guru from Afar
      parent: Prayers
created_at: '2022-03-01T03:10:18.232307'
last_modified_at: '2022-03-01T03:10:18.232309'
statistics:
  total_words: 10563
  total_non_words: 651
quality:
  non_words_ratio: 0.06
